version: '2.1.{build}'
image: Visual Studio 2017

before_build:
- cmd: nuget restore

build_script:
    - cmd: dotnet pack -p:PackageVersion=%APPVEYOR_BUILD_VERSION%
    - cmd: dotnet pack -c Debug -p:PackageVersion=%APPVEYOR_BUILD_VERSION%


#test_script:
  # run the unit tests (requires changing into the test directory)
 # - cmd: cd tests
#- cmd: dotnet nunit

cmd: donet OpenCover.Console.exe 
#-register:user -target:".\packages\xunit.runner.console.2.4.1\tools\net471\xunit.console.x86.exe" -targetargs:".\UnitTests\bin\Debug\UnitTests.dll -noshadow" -filter:"+[LeedCodeLib*]* -[UnitTests*]*" -output:".\MyProject_coverage.xml"

#.\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:".\packages\xunit.runner.console.2.4.1\tools\net471\xunit.console.x86.exe" -targetargs:".\UnitTests\bin\Debug\UnitTests.dll -noshadow" -filter:"+[LeedCodeLib*]* -[UnitTests*]*" -output:".\MyProject_coverage.xml"

#upload_report
#- .\packages\Codecov.1.1.0\tools\codecov.exe -f "MyProject_coverage.xml"