version: '2.1.{build}'
image: Visual Studio 2017

clone_depth: 1

build_script:
    - cmd: dotnet pack -p:PackageVersion=%APPVEYOR_BUILD_VERSION%
    - cmd: dotnet pack -c Release -p:PackageVersion=%APPVEYOR_BUILD_VERSION%
 #   - cmd: dotnet test -p:PackageVersion=%APPVEYOR_BUILD_VERSION% test/NUnit.Xml.TestLogger.UnitTests/NUnit.Xml.TestLogger.UnitTests.csproj
 #   - cmd: dotnet test -p:PackageVersion=%APPVEYOR_BUILD_VERSION% test/NUnit.Xml.TestLogger.AcceptanceTests/NUnit.Xml.TestLogger.AcceptanceTests.csproj


#upload report
#- .\packages\Codecov.1.1.0\tools\codecov.exe -f "MyProject_coverage.xml"